recipe_search/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from accounts import views as accounts_views
from recipes import views as recipes_views
from search import views as search_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/signup', accounts_views.signup, name='signup'),
    path('account/profile', accounts_views.profile, name='profile'),
    path('account/update', accounts_views.update, name='update'),
    path('account/delete', accounts_views.delete, name='delete'),
    path('account/login', accounts_views.user_login, name='login'),
    path('logout', accounts_views.user_logout, name='logout'),
    path('recipe/create', recipes_views.create_recipe, name='recipeCreate'),
    path('recipe/details/<int:rid>',
         recipes_views.recipe_details, name='details'),
    path('recipe/update/<int:rid>',
         recipes_views.update_recipe, name='recipeUpdate'),
    path('recipe/list', recipes_views.show_list, name='userList'),
    path('recipe/vote/<int:rid>', recipes_views.add_vote_result, name='vote'),
    path('', search_views.landing, name='landing'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/models.py
"""
Models for the recipes created by users
"""
from django.db import models
from django.urls import reverse

from accounts.models import MyUser


class Categories(models.Model):
    """
    Classify recipes by categories
    All recipes have a category
    Categories have a name
    """
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name


class Content(models.Model):
    """
    Recipe content
    Links ingredients and recipes with a quantity for each ingredient
    """
    recipe = models.ForeignKey("Recipes", on_delete=models.CASCADE)
    index = models.SmallIntegerField(null=False)
    instructions = models.TextField()
    creation_date = models.DateTimeField(auto_now_add=True)
    modification_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["index"]


class Ingredients(models.Model):
    """
    Table of all the ingredients used in the recipes
    """
    recipe = models.ForeignKey("Recipes", on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    quantity = models.CharField(max_length=255)
    creation_date = models.DateTimeField(auto_now_add=True)
    modification_date = models.DateTimeField(auto_now=True)


class Recipes(models.Model):
    """
    Recipes contains the following fields:
        a name, a creator, a category, a list of ingredients, and a rating
    """
    name = models.CharField(max_length=255)
    rating = models.JSONField(null=True)
    creator = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    category = models.ForeignKey("Categories", on_delete=models.CASCADE)
    creation_date = models.DateTimeField(auto_now_add=True)
    modification_date = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        """method to create the url for a specific recipe"""
        return reverse("details", args=[int(self.id)])

recipes/forms.py
"""
Forms to create and update a recipe
"""
from django.forms import ModelForm, CharField, TextInput, Select, \
                         ModelChoiceField
from django.forms.models import inlineformset_factory

from .models import Categories, Ingredients, Content, Recipes


class RecipeNameForm(ModelForm):
    """
    This forms allows the creation of a recipe
    """

    class Meta:
        model = Recipes
        fields = ["name", "category"]

    name = CharField(label="Nom de la recette", required=True, max_length=255,
                     widget=TextInput(attrs={"class": "col-8"}))
    category = ModelChoiceField(queryset=Categories.objects.all(),
                                empty_label=None, label="Catégorie",
                                widget=Select(attrs={"class": "col-7"}))


class IngredientForm(ModelForm):
    """
    ModelForm for an ingredient, to be used in a formset
    """

    class Meta:
        model = Ingredients
        fields = ["name", "quantity"]
        labels = {
            "name": "Ingrédient",
            "quantity": "Quantité"
        }


IngredientsFormSet = inlineformset_factory(Recipes, Ingredients,
                                           form=IngredientForm, extra=1,
                                           fields=["name", "quantity"],
                                           can_delete=True)


class ContentForm(ModelForm):
    """
    ModelForm for a content entry, to be used in a formset
    """

    class Meta:
        model = Content
        fields = ["instructions"]
        labels = {
            "instructions": "Etape"
        }


ContentFormSet = inlineformset_factory(Recipes, Content, form=ContentForm,
                                       extra=1, fields=["instructions"],
                                       can_delete=True)

recipes/views.py
"""
views for the recipes app
"""
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from .forms import RecipeNameForm, IngredientsFormSet, ContentFormSet
from .models import Recipes, Ingredients, Content


@login_required
def create_recipe(request):
    """A page to create a new recipe"""
    recipe = RecipeNameForm()
    ingredients = IngredientsFormSet(prefix="ingredient")
    steps = ContentFormSet(prefix="step")
    if request.method == "POST":
        recipe = RecipeNameForm(request.POST)
        ingredients = IngredientsFormSet(request.POST, prefix="ingredient")
        steps = ContentFormSet(request.POST, prefix="step")
        if recipe.is_valid() and ingredients.is_valid() and steps.is_valid():
            new_recipe = recipe.save(commit=False)
            new_recipe.creator = request.user
            new_recipe.save()
            for form in ingredients.forms:
                if form.cleaned_data:
                    ingredient = form.save(commit=False)
                    ingredient.recipe = new_recipe
                    ingredient.save()
            for num, form in enumerate(steps.forms):
                if form.cleaned_data:
                    step = form.save(commit=False)
                    step.recipe = new_recipe
                    step.index = num
                    step.save()
            return redirect(new_recipe.get_absolute_url())
        return render(request, "recipes/create.html",
                      {"recipe": recipe, "ingredients": ingredients,
                       "steps": steps})
    return render(request, "recipes/create.html",
                  {"recipe": recipe, "ingredients": ingredients,
                   "steps": steps})


@login_required
def update_recipe(request, rid):
    """A page to update an existing recipe"""
    recipe = get_object_or_404(Recipes, id=rid)
    recipe_form = RecipeNameForm(request.POST or None, instance=recipe)
    ingredients_formset = IngredientsFormSet(request.POST or None,
                                             prefix="ingredient",
                                             instance=recipe)
    steps_formset = ContentFormSet(request.POST or None, prefix="step",
                                   instance=recipe)
    if request.method == "POST":
        if recipe_form.is_valid() and ingredients_formset.is_valid() and \
                steps_formset.is_valid():
            recipe_form.save()
            ingredients_formset.save()
            steps_formset.save(commit=False)
            for num, obj in enumerate(steps_formset.new_objects):
                obj.index = num
                obj.save()
            steps_formset.save()
            return redirect(recipe.get_absolute_url())
        return render(request, "recipes/update.html",
                      {"recipe": recipe_form,
                       "ingredients": ingredients_formset,
                       "steps": steps_formset})
    return render(request, "recipes/update.html",
                  {"recipe": recipe_form, "ingredients": ingredients_formset,
                   "steps": steps_formset})


def recipe_details(request, rid):
    """A page displaying the content of a recipe"""
    recipe = get_object_or_404(Recipes.objects.filter(id=rid))
    ingredients = Ingredients.objects.filter(recipe_id=recipe.id)
    steps = Content.objects.filter(recipe_id=recipe.id)
    rating = recipe.rating
    return render(request, "recipes/details.html",
                  {"recipe": recipe, "ingredients_list": ingredients,
                   "steps_list": steps, "rating": rating})


@login_required
def show_list(request):
    """A page displaying all the user's recipe"""
    user = request.user
    recipes = Recipes.objects.filter(creator=user)
    return render(request, 'recipes/list.html', {"results": recipes})


@login_required
def add_vote_result(request, rid):
    """Add user vote result to recipe vote tally"""
    if request.method == "POST":
        recipe = get_object_or_404(Recipes.objects.filter(id=rid))
        old_rating = recipe.rating
        new_rating = {}
        if old_rating:
            liked = old_rating["liked"] + 1
            total = old_rating["total votes"] + 1
            new_rating["liked"] = liked
            new_rating["total votes"] = total
            recipe.rating = new_rating
            recipe.save()
        else:
            new_rating = {"liked": 1, "total votes": 1}
            recipe.rating = new_rating
            recipe.save()
        result = {"status": "success", "rating": new_rating}
        return JsonResponse(result)

templates/recipes/create.html
{% extends 'search/base.html' %}
{% load static %}
{% load crispy_forms_filters %}
{% load crispy_forms_field %}

{% block content %}

  <section class="page-section cta" id="signup">
    <div class="container">
      <div class="mx-auto">
        <div class="cta-inner text-center rounded">
          <form class="mx-auto" method="post" enctype="multipart/form-data" id="recipeForm">
            {% csrf_token %}
            {% for field in recipe %}
              <div class="form-row text-left">
                <div class="form-group">
                  <label for="{{ field.auto_id }}" class="col-form-label-lg mr-auto">{{ field.label }}</label>
                  {{ field }}
                </div>
              </div>
            {% endfor %}
            <div class="text-left">
              <label id="ingredients" class="col-form-label-lg">Ingredients</label>
              <div id="ingredients_list">
                <table>
                  {{ ingredients.management_form|crispy }}
                  {% for form in ingredients.forms %}
                    <tr class="formset_row-{{ ingredients.prefix }}">
                      {% for field in form.visible_fields %}
                        <td>
                          {# Include the hidden fields in the form #}
                          {% if forloop.first %}
                            {% for hidden in form.hidden_fields %}
                              {{ hidden }}
                            {% endfor %}
                          {% endif %}
                          {{ field.errors.as_ul }}
                          {{ field|as_crispy_field }}
                        </td>
                      {% endfor %}
                    </tr>
                  {% endfor %}
                </table>
              </div>
            </div>
            <div class="mx-auto">
              <div class="text-left">
                <label for="id_recipe" class="col-form-label-lg">Recette</label>
                <table id="steps_list">
                    {{ steps.management_form|crispy }}
                    {% for form in steps.forms %}
                      <tr class="formset_row-{{ steps.prefix }}">
                        {% for field in form.visible_fields %}
                          <td>
                            {# Include the hidden fields in the form #}
                            {% if forloop.first %}
                              {% for hidden in form.hidden_fields %}
                                {{ hidden }}
                              {% endfor %}
                            {% endif %}
                            {{ field.errors.as_ul }}
                            {{ field|as_crispy_field }}
                          </td>
                        {% endfor %}
                      </tr>
                    {% endfor %}
                  </table>
              </div>
            </div>
          </form>
          <button type="submit" class="btn btn-outline-primary mt-3" form="recipeForm">Créer la recette</button>
        </div>
      </div>
    </div>
  </section>
  <br>

{% endblock %}

{% block scripts %}
  <script src="{% static 'recipes/js/libs/dynamic_formset/jquery.formset.js' %}"></script>
  <script type="text/javascript">
      $('.formset_row-{{ ingredients.prefix }}').formset({
          addText: 'add another',
          deleteText: 'remove',
          prefix: '{{ ingredients.prefix }}',
      });
      $('.formset_row-{{ steps.prefix }}').formset({
          addText: 'add another',
          deleteText: 'remove',
          prefix: '{{ steps.prefix }}',
      });
  </script>
{% endblock %}

templates/recipes/details.html
{% extends 'search/base.html' %}
{% load static %}

{% block content %}

  <section class="page-section">
    <div class="container">
      <div class="product-item">
        <div class="product-item-title d-flex">
          <div class="bg-faded p-5 d-flex m-auto rounded">
          <span>
            <h2 class="section-heading mb-0">
              <span class="section-heading-upper">{{ recipe.category }}</span>
              <span class="section-heading-lower">{{ recipe.name }}</span>
            </h2>
            {% if user.is_authenticated %}
              <a class="btn btn-primary mt-2" href={% url 'recipeUpdate' rid=recipe.id %}>Mettre a jour</a>
            {% endif %}
          </span>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section class="page-section">
    <div class="container">
      <div class="product-item">
        <div class="product-item-title d-flex">
          <div class="bg-faded p-5 d-flex mr-auto rounded mb-3">
            <h2 class="section-heading mb-0">
              <span class="section-heading-upper">Les Ingrédients</span>
            </h2>
          </div>
        </div>
        {% if ingredients_list %}
          <div class="product-item-description d-flex ml-auto">
            <div class="bg-faded p-5 rounded">
              <ul>
                {% for ingredient in ingredients_list %}
                  <li>
                    <p>{{ ingredient.name }} : {{ ingredient.quantity }}</p>
                  </li>
                {% endfor %}
              </ul>
            </div>
          </div>
        {% else %}
          <div class="product-item-description d-flex ml-auto">
            <div class="bg-faded p-5 rounded"><p class="mb-0">Cette recette n'a pas d'ingrédients</p></div>
          </div>
        {% endif %}
      </div>
    </div>
  </section>
  <section class="page-section">
    <div class="container">
      <div class="product-item">
        <div class="product-item-title d-flex">
          <div class="bg-faded p-5 d-flex mr-auto rounded mb-3">
            <h2 class="section-heading mb-0">
              <span class="section-heading-upper">Les Etapes</span>
            </h2>
          </div>
        </div>
        {% if steps_list %}
          <div class="product-item-description d-flex ml-auto">
            <div class="bg-faded p-5 rounded">
              {% for step in steps_list %}
                <li>
                  <p>{{ step.instructions }}</p>
                </li>
              {% endfor %}
            </div>
          </div>
        {% else %}
          <div class="product-item-description d-flex ml-auto">
            <div class="bg-faded p-5 rounded"><p class="mb-0">Cette recette n'a pas d'etapes</p></div>
          </div>
        {% endif %}
      </div>
    </div>
  </section>
  <section class="page-section">
    <div class="container my-2">
      <a class="btn btn-primary mt-2" onClick="copyUrl('{{ request.build_absolute_uri }}')">Copier le lien de cette recette</a>
    </div>
    <div class="container my-2">
      {% if user.is_authenticated %}
        {% csrf_token %}
        <button class="btn btn-outline-light"><i class="fas fa-thumbs-up fa-2x"></i></button>
        {% if recipe.rating == None %}
          <span class="mx-2" id="rating">0</span>
        {% else %}
          <span class="mx-2" id="rating">{{ rating.liked }}</span>
        {% endif %}
  {% endif %}
    </div>
  </section>

{% endblock %}

{% block scripts %}
    <script>
      function copyUrl(uri) {
        navigator.clipboard.writeText(uri)
      }

      const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
      document.addEventListener('DOMContentLoaded', function () {
        $('button').on('click', function () {
          $.ajax({ url: "{% url "vote" rid=recipe.id %}", type: "POST", dataType: 'json', headers: {'X-CSRFToken': csrftoken},
              success: function (response) {
                $('#rating').text(response.rating.liked);
          }});
        });
      });
    </script>
{% endblock %}

templates/recipes/update.html
{% extends 'search/base.html' %}
{% load static %}
{% load crispy_forms_filters %}
{% load crispy_forms_field %}
{% block content %}

  <section class="page-section cta" id="signup">
    <div class="container">
      <div class="mx-auto">
        <div class="cta-inner text-center rounded">
          <form class="mx-auto" method="post" enctype="multipart/form-data" id="recipeForm">
            {% csrf_token %}
            {% for field in recipe %}
              <div class="form-row text-left">
                <div class="form-group">
                  <label for="{{ field.auto_id }}" class="col-form-label-lg mr-auto">{{ field.label }}</label>
                  {{ field }}
                </div>
              </div>
            {% endfor %}
            <div class="text-left">
              <label id="ingredients" class="col-form-label-lg">Ingredients</label>
              <div id="ingredients_list">
                <table>
                  {{ ingredients.management_form|crispy }}
                  {% for form in ingredients.forms %}
                    <tr class="formset_row-{{ ingredients.prefix }}">
                      {% for field in form.visible_fields %}
                        <td>
                          {# Include the hidden fields in the form #}
                          {% if forloop.first %}
                            {% for hidden in form.hidden_fields %}
                              {{ hidden }}
                            {% endfor %}
                          {% endif %}
                          {{ field.errors.as_ul }}
                          {{ field|as_crispy_field }}
                        </td>
                      {% endfor %}
                    </tr>
                  {% endfor %}
                </table>
              </div>
            </div>
            <div class="mx-auto">
              <div class="text-left">
                <label for="id_recipe" class="col-form-label-lg">Recette</label>
                <table id="steps_list">
                    {{ steps.management_form|crispy }}
                    {% for form in steps.forms %}
                      <tr class="formset_row-{{ steps.prefix }}">
                        {% for field in form.visible_fields %}
                          <td>
                            {# Include the hidden fields in the form #}
                            {% if forloop.first %}
                              {% for hidden in form.hidden_fields %}
                                {{ hidden }}
                              {% endfor %}
                            {% endif %}
                            {{ field.errors.as_ul }}
                            {{ field|as_crispy_field }}
                          </td>
                        {% endfor %}
                      </tr>
                    {% endfor %}
                  </table>
              </div>
            </div>
          </form>
          <button type="submit" class="btn btn-outline-primary mt-3" form="recipeForm">Mettre a jour la recette</button>
          <a class="btn btn-outline-secondary mt-3 ml-lg-4" href="{% url 'userList' %}">Annuler</a>
        </div>
      </div>
    </div>
  </section>
  <br>

{% endblock %}

{% block scripts %}
  <script src="{% static 'recipes/js/libs/dynamic_formset/jquery.formset.js' %}"></script>
  <script type="text/javascript">
      $('.formset_row-{{ ingredients.prefix }}').formset({
          addText: 'add another',
          deleteText: 'remove',
          prefix: '{{ ingredients.prefix }}',
      });
      $('.formset_row-{{ steps.prefix }}').formset({
          addText: 'add another',
          deleteText: 'remove',
          prefix: '{{ steps.prefix }}',
      });
  </script>
{% endblock %}